### ISSUE TITLE
Deprecated use of `loop` kwarg to `asyncio.Semaphore` in `base_loop.py`

### ISSUE THREAD

**Issue by amrishparmar** [gistart/asyncio-pool#5]
When using this library I get this warning when running my tests.

```
  /usr/local/lib/python3.8/site-packages/asyncio_pool/base_pool.py:34: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
    self.semaphore = aio.Semaphore(value=self.size, loop=self.loop)
```

Currently just suppressing this warning for the moment, but would be good to have a fix even if Python 3.10 is a while off.

**Comment by smithk86** [comment]
This is not the only issue with 3.8. I was actually going to fix this and submit a pull request but the unit tests will not pass on 3.8. Looking into it now.

**Comment by gistart** [comment]
> This is not the only issue with 3.8. I was actually going to fix this and submit a pull request but the unit tests will not pass on 3.8. Looking into it now.

Tests pass w/ recent PR from @FichteFoll https://github.com/gistart/asyncio-pool/actions/runs/195038423

**Comment by gistart** [comment]
fixed https://github.com/gistart/asyncio-pool/pull/6

**Comment by amrishparmar** [comment]
Thanks for the fast turnaround. Can confirm the issue is resolved in our application
