### ISSUE TITLE
Unit tests fail with Python 3.8

### ISSUE THREAD

**Issue by smithk86** [gistart/asyncio-pool#7]
I have been looking into this as well and thought maybe we could collaborate. One issue I have been looking at is BaseAioPool.cancel(). It appears even when you cancel the Task, the Future is behaving differently then it does in 3.7.

In 3.7, the Future contains asyncio.CancelledError but in 3.8 it is asyncio.InvalidStateError. It also seems like there is an underlying Future still running when is holding up BaseAioPool.join().

**Comment by gistart** [comment]
Thanks, I will look into this a bit later.

Tests pass without warnings now, btw: https://github.com/gistart/asyncio-pool/actions/runs/195066427

**Comment by smithk86** [comment]
I had not properly pulled in all the changes. Test are good for me now. Thanks!
